Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-vbguest"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.box = "31z4/boot2docker"
  config.vm.box_version = "18.01.0"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provision "docker",
    images: ["mholdg16/miyoomini-toolchain:latest"]

  config.vm.provision "shell", inline: <<-SHELL
    sed -in 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /usr/local/etc/ssh/sshd_config
    sed -in 's/^#PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /usr/local/etc/ssh/sshd_config
    sed -in 's/^#PrintMotd yes/PrintMotd no/g' /usr/local/etc/ssh/sshd_config
    echo '#!/bin/bash' > /var/lib/boot2docker/bootlocal.sh
    echo 'passwd -d docker' >> /var/lib/boot2docker/bootlocal.sh
    echo 'passwd -d root' >> /var/lib/boot2docker/bootlocal.sh
    echo 'echo "cd /vagrant" >> /home/docker/.ashrc' >> /var/lib/boot2docker/bootlocal.sh
    echo 'echo "docker run -it --rm -v /vagrant/workspace:/root/workspace mholdg16/miyoomini-toolchain:latest /bin/bash" >> /home/docker/.ashrc' >> /var/lib/boot2docker/bootlocal.sh
    echo 'echo "exit" >> /home/docker/.ashrc' >> /var/lib/boot2docker/bootlocal.sh
    echo 'Vagrant box provisioned !'
    echo '"vagrant up" to power up'
    echo '"vagrant ssh" to connect or via ssh@localhost:2222 (user: docker, pass: empty)'
    echo '"vagrant halt" to shut down'
    echo '"vagrant destroy" to clean up and destroy'
    echo 'Shutting down now...'
    shutdown -h now
  SHELL
end
